### ISSUE TITLE
As a speedgolfer, I want to be able to tell the app when I’m done with a hole and what my score was so that I can automatically record my speedgolf rounds as I play.

### ISSUE THREAD

**Issue by chundhau** [wsu-cpts421-sp21/speedgolf-demo#1]
# Acceptance Criteria

- [x] User can verbally indicate they are done with hole.
- [x] User receives auditory feedback that they are done with hole.
- [ ] user can undo being done with hole.
- [ ] User can verbally indicate their hole score.
- [ ] User receives auditory feedback on hole score that was registered.
- [ ] User can correct hole score.

...

# Implementation Todos

Front end:

- [ ] Second thing that must be done in the front end code.
...
- [ ] First thing that must be done in the front end code.

Back end:

- [ ] First thing that must be done in the back end code.
- [ ] Second thing that must be done in the back end code.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...
